### ISSUE TITLE
file_exists doesn't work?

### ISSUE THREAD

**Issue by Blaxus** [Respect/Rest#124]
So I was using Macaw originally...

```php
use \NoahBuscher\Macaw\Macaw;
Macaw::get('/(:any)', function($controller) {
    $path = 'controllers/'.$controller.'.php';
    if (file_exists($path)) {
        echo "The file $path exists";
    } else {
        echo "The file $path does not exist";
    }
});
Macaw::dispatch();
```
```php
use Respect\Rest\Router;
$r3 = new Router;
$r3->get('/*', function($controller) {
    $path = 'controllers/'.$controller.'.php';
    if (file_exists($path)) {
        echo "The file $path exists";
    } else {
        echo "The file $path does not exist";
    }
});
```

> Warning: include(controllers/bla.php): failed to open stream: No such file or directory in ...

For some reason, it says that this file doesn't exist. Is there a reason file_exists doesn't work here? Obviously I could do it without using file_exists but then the whole thing breaks when you try to load a non-existing file.

**Comment by augustohp** [comment]
The differences between [Macaw][] and [Rest][] should not have any effect on the code you presented. 

For the first time in my life, pointing you to [PHP's manual][man] won't help you. So lets make an exchange: I try to help you and you make that PHP documentation page look better, what do you think?

`file_exists` checks the file relative to the path from where the script is being executed. You probably want `file_exists(__DIR__.$path)` which checks for the full path of the file, where `__DIR__` is expanded to the directory of the file being executed.

[Macaw]: https://github.com/noahbuscher/Macaw
[Rest]: https://github.com/Respect/Rest
[man]: http://php.net/file_exists

**Comment by Blaxus** [comment]
@augustohp Thanks, you just saved my bacon!

Can't make any promises about the PHP Manual. I'll look into it. But you're right there's no note about it anywhere, I'm sure I would'v seen it if it was in there.

**Comment by augustohp** [comment]
> Can't make any promises about the PHP Manual. I'll look into it. But you're right there's no note about it anywhere, I'm sure I would'v seen it if it was in there.

Ask around the doc mailing list man, try to give back to the community. I am sure you will learn a lot of things along the way.

**Comment by augustohp** [comment]
I will try to give you some background on the issue: this is "obvious" to people with a considerable unix background - meaning: it is not obvious other than to the people who made it and use the same design guidelines until today (which have been time proof).

Everything on unix is a file, there is a permission to allow a file to be executed. You know some of these "files": `ls`, `cd`, `php`, etc...
How come you can type those "files" without their full path? Everyone can agree that typing their full path every time would be painful enough so there is the `$PATH` variable. This variable contains a list of directories separated by a `:` (comma) so every time you type (execute - remeber the permission) something which cannot be currently found on the path relative to where you are (where you `cd`ed to) the shell goes for the `$PATH` variable and tried to find that on every directory in there.

PHP uses the exact same strategy. Instead of the `$PATH` we have the [include_path()](http://php.net/manual/en/ini.core.php#ini.include-path) which works in the very same way but PHP also uses it for non executable files. So, that is why when you execute PHP the "relative path" is not the one from the script being interpreted, it is the one from where the script has been executed. As Apache/NGINX/etc executes the script based on the document root configured PHP's relative path is always the document root. 
As a design decision (which I don't agree) of Composer, they completely ignored the include path to always use the full path of everything (meaning that you would never need to rely on the `include_path`).

That is why the `___DIR__` expansion comes in handy. Prior to composer (Pear days) we were used to define and maintain the include path and so we were aware of it. With composer you simply are not aware of that "design" and the most obvious thing to think is that the "relative path" is the one of the current script.

PS: This may well become a good entry in "PHP the right way". It should be easier to add it there than into the manual itself (less rules).
