### ISSUE TITLE
Explode as an array when the post parameter is a raw

### ISSUE THREAD

**Issue by ogallardop** [Respect/Rest#128]
some time post parameter has no name for example

```
{
	"fec_reg": "06/05/2016 15:31:45",
	"id_funcionario": 241,
	"lat": "4.6813042444406205",
	"lon": "-74.06172417576595",
	"id_pdv": 1037
}
```

the idea is to use 

`file_get_contents('php://input')`

to get the value of parameters

**Comment by augustohp** [comment]
I don't get what is the problem here, you care to explain a little further how can we modify the library to better fit your needs?

We do encourage people to ~~use~~ respect PHP whenever possible, does the library prevents you from doing on the scenario you described?

PS: I am closing the issue but feel free to comment on it, we will still be 👀 .
